name: Deploy to Firebase Hosting on merge

on:
    push:
        branches:
            - main

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20
            - name: Install dependencies
              run: npm ci && npm run build
            - name: Set environment variables
              run: |
                  echo "REACT_APP_GOOGLE_API_KEY=${{ secrets.REACT_APP_GOOGLE_API_KEY }}" >> .env
                  echo "REACT_APP_apiKey=${{ secrets.REACT_APP_apiKey }}" >> .env
                  echo "REACT_APP_authDomain=${{ secrets.REACT_APP_authDomain }}" >> .env
                  echo "REACT_APP_projectId=${{ secrets.REACT_APP_projectId }}" >> .env
                  echo "REACT_APP_storageBucket=${{ secrets.REACT_APP_storageBucket }}" >> .env
                  echo "REACT_APP_messagingSenderId=${{ secrets.REACT_APP_messagingSenderId }}" >> .env
                  echo "REACT_APP_appId=${{ secrets.REACT_APP_appId }}" >> .env
                  echo "REACT_APP_measurementId=${{ secrets.REACT_APP_measurementId }}" >> .env
                  echo "REACT_APP_databaseURL=${{ secrets.REACT_APP_databaseURL }}" >> .env
            - name: Deploy to Firebase Hosting
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOBILEINVITATION_F5217 }}'
                  channelId: live
                  projectId: mobileinvitation-f5217
